site_name: midgy literate programming
site_description: midgy literate programming
site_url: https://deathbeds.github.io/midgy
repo_url: https://deathbeds.github.io/midgy
repo_name: deathbeds/midgy
site_dir: site

theme:
  name: material

plugins:
  - search

nav:
  - midgy literate programming: 
      - midgy literate programming: README.md
      - midgy usage: midgy.md
  - the midgy language:
      - about the language: language/README.md
      - midgy basics: language/basics.md
      - code fences: language/code_fences.md
      - doctests: language/doctest.md
      - front matter: language/front_matter.md
      - line continuations: language/line_continuations.md
      - rendering flags: language/flags.md
      - IPython magics: language/magics.md
      - IPython magics: language/container_blocks.md
      - mixed code tokens: language/mixed.md
  - the midgy design: design.md
  - sample programs:
    - typer applications with midgy: programs/command-line-with-typer.md

markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - footnotes
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: "¤"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
